### ISSUE TITLE
Unpaired p tag

### ISSUE THREAD

**Issue by SwitWu** [bdtc/lwarp#12]
Here is a minimal tex file:

```tex
% main.tex
\documentclass[doc2]{ltxdoc}
\usepackage[mathjax]{lwarp}
\setcounter{FileDepth}{1}
\setcounter{SideTOCDepth}{1}
\begin{document}
\section{Introduction}
some text and some formula $a = b + c$
\end{document}
```

After `pdflatex main` and `lwarpmk html`, the resulting file `Introduction.html` has 4 `<p>` tags but 3 `</p>` tags. The unpaired `<p>` tag appears on line 372 after the `class="hidden"` div.

**Comment by bdtc** [comment]
Got it.  Fixed in the upcoming v0.914.
