### ISSUE TITLE
Formatting adds unwanted text spaces

### ISSUE THREAD

**Issue by marekkolman** [bdtc/lwarp#22]
Lwarp adds whitespaces when text is formatted

LaTeX:
```latex
we are in a (\textit{multi--currency}) world
```
Rendered PDF -> no whitespace around `multi-currency`:
![CleanShot 2024-03-26 at 21 08 24](https://github.com/bdtc/lwarp/assets/25546774/15fc5651-e9fa-4604-a150-543603279395)

Rendered HTML -> contains whitespace around `multi-currency`:
![CleanShot 2024-03-26 at 21 09 00](https://github.com/bdtc/lwarp/assets/25546774/61703efd-e8dd-409c-a5cd-0288ccc69f29)
I highlighted with a cursor that it is actually a true whitespace.

**Comment by bdtc** [comment]
Hi,
No problem seen when I test it here.
What version of lwarp do you have?
And what font are you using?
Thanks

**Comment by marekkolman** [comment]
Hello, 
thanks for the prompt reply! No issue with Lwarp eventually, apologies. But if you didn't check it, I'd have been still running around. 

I do post processing of the HTML via python's BeautifulSoup library this library added the whitespace when `prettify()` function was called on Lwarp's HTML.
